### ISSUE TITLE
Nurturing home wanted

### ISSUE THREAD

**Issue by dekellum** [dekellum/hyperx#1]
Originally, an official hyper header (name TBD) module crate was requested in hyperium/hyper#189, 4 years ago. 

Speaking of cute/snarky crate names, consider either of the following pronunciations of hyper*x*:

* /ˈhīpər ˈeks/
* /hī ˈpərks/

I'd be happy to transfer/contribute this to the hyperium organization if the goals for such a crate are well aligned.

**Comment by lnicola** [comment]
It's not very clear to me what the purpose of this crate is. Right now it can be used to port apps from `hyper` 0.11 to 0.12. It can stay like this, or it can become a strongly-typed layer for the headers in the `http` crate, which would mean dropping the `Headers` and related types, and probably changing how parsing and formatting work.

In the latter case, there would no longer be a connection to `hyper`.

Related projects it might be worth looking into: https://github.com/sfackler/typed-headers, https://github.com/pyfisch/httpdate.

**Comment by dekellum** [comment]
@Inicola, I agree with your summary on the current and potential future purpose of this fork.

My goal was to fill an obvious hole in the upgrade story from `hyper` 0.11 to 0.12, quickly and with minimal effort. @sfackler, mentioned he was [prototyping](https://github.com/hyperium/hyper/issues/189#issuecomment-360634791) back in January, and its good to see that he has new commits there in the last week.

Judging from commits, the `hyper` developers put a fair amount of work into the correctness of the typed-header parsing and serialization, which is preserved here, along with some legacy baggage given that it predates the `http` crate.  If it was easy enough to remove and replace the latter while keeping the robustness of the former, it would be worth continuing here.  That at least one of the hyper contributor's thinks a rewrite is more compelling, is definitely worth noting however.

Other then the *hyperx* crate name, there is no direct connection or dependency on hyper (master) as of now (and in either case).

**Comment by lnicola** [comment]
I think @seanmonstar might be willing to pick this one up: https://github.com/hyperium/headers/ (it's a little better than this repository in that it has a proper history of the code, without the extra files).

If you're fine with that, I suggest starting by cherry-picking some commits from your repository, then cleaning up the old code a little (e.g. by dropping `Headers`). How do you feel about this plan?

**Comment by dekellum** [comment]
Regarding the git history, @lnicola , I assume you mean in this new hyperium/headers publishing (which I haven't yet looked at in any details) the same or similar code has had `git filter-branch` or similar applied such that only historic commits pertaining to headers are included, in an albeit mutated form.  Your use of *better*, is therefore subjective. With hyperx, the providence and changes are quite clear, as from the CHANGELOG.md here:

> Forked from hyper 0.11.27, e*x*tracting the typed *header* module
> from [hyperium/hyper@76fdbcf2], 0.11.x branch, preserved here as
> [76fdbcf2].

Where as, that will not be very easy to determine after filter-branch replaces all the commits in a fashion similar to a total rebase.

[hyperium/hyper@76fdbcf2]: https://github.com/hyperium/hyper/commit/76fdbcf2
[76fdbcf2]: https://github.com/dekellum/hyperx/commit/76fdbcf23cd35cebb03bf4c0e3025b671578bd75

Beyond that minor point, I don't follow what you are suggesting in terms of moving forward.  Could you clarify?   Assuming there is common interest and this isn't being done better by these other projects, I would think `hyperx::header::Headers` would get deprecated first, and only after some better integration is found with `http::HeaderMap`?  @sfackler's typed-headers (your link above) seems to include some good ideas on how to do that integration, but I also haven't spent much time/thought on it.

**Comment by lnicola** [comment]
> Your use of better, is therefore subjective.

Fair enough. I meant that it can be a new crate (similar in spirit to `http`, hopefully used by a larger part of the ecosystem) whose provenance is less important, and which doesn't try to keep any semblance of ~~compatibility~~ relationship with `hyper 0.11`.

> I don't follow what you are suggesting in terms of moving forward.

1. Apply some of the `hyperx` commits to the new `headers` repository -- it seemed fair to ask here since you've authored them.
2. Move forward with the clean-ups and API changes (the `http` port) in the `headers` crate.
3. Keep `hyperx` as-is or deprecate it, depending on your preference, and continue the development in the `headers` repository.

I agree that `typed-headers` seems cleaner, but it still seems a bit allocation-heavy and is less complete, so maybe starting from the old `hyper` code isn't such a bad idea.

**Comment by dekellum** [comment]
hyperx has been published on crates.io as a "new crate", but you must mean something else.  :)

I've kept the same licensing terms as the orginal hyper, so you can certainly re-purpose anything you find useful here with my work (consent granted), and with their consent, other contributors work.  But given observed behavior with the associated projects, I'm not seeing your 3rd party suggestions here as a terribly encouraging invitation to spend more time *trying* to contribute new work to hyperium(/headers). I hope you can understand that!

Also the emphasis on ASAP removal of `hyperx::header::Headers`, and of course the original removal of the header module for 0.12 in the first place,  suggest a different mindset and less emphasis on providing a painless upgrade path for existing users of the header module.

**Comment by lnicola** [comment]
> Also the emphasis on ASAP removal of hyperx::header::Headers,  and of course the original removal of the header module for 0.12 in the  first place,  suggest a different mindset and less emphasis on  providing a painless upgrade path for existing users of the header  module.

Indeed, I don't think there are any plans to keep full compatibility with the `hyper 0.11` users. It's a new crate that happens to start from older code.

About the "ASAP removal" of `Headers` (and I was talking above about `headers::Headers`, not `hyperx::header::Headers`), it was just my idea. I'm not really affiliated with `hyper` or any other project. I only posted here to let you and other readers know about the new crate, in case they want to use and/or contribute to it in the future.

And sorry if this came out as offensive in any way, it wasn't intended.

**Comment by dekellum** [comment]
Thanks much for that, and no offense assumed or taken.

**Comment by dekellum** [comment]
6 months after the initial 0.12.0 release, hyperx has seen enough use to justify publishing the crate and maintaining compatibility.   In the 0.14.0 release, #8 makes selective parsing of `http::header::HeaderValue`(s) to typed-headers more (and I think for most use cases, adequately) efficient. 

Meanwhile [hyperium/headers](https://github.com/hyperium/headers) has had intermittent and more recent activity since it was mentioned (above) in July, more so than [sfackler/typed-headers](https://github.com/sfackler/typed-headers).  The former might be the _heir apparent_, as per hyperium/http#264, where it would hopefully be released with some stability guarantees. 

Depending on continued interest, there remain possible future steps for `hyperx::header`, in no particular order:

* Deprecate/replace the local `Raw` with the `HeaderValue` type in `hyperx::header::Headers`, making conversions to `Headers` more efficient.

* Offer an extension trait for typed set/get for `http::HeaderMap`, enabling a nicer incremental migration path _off_ of the `Headers` type, while maintaining continuity with the header types defined here. 

* As inherited from *hyper*, error handling in `hyperx::header` is rather severe and lacks good error-types or other classification. That style appears to continue in _hyperium/headers_. More lenient parsing, with clear errors or warnings, would be more appropriate for parsing HTTP headers on the public internet. 

The original stated desire for *Official* support, or to sway the *hyper* 0.12 decision to drop the module and regress on the feature for 6+ months, obviously didn't happened.  Nevertheless some nurturing, mindful of compatibility, has occurred since and may continue here. Closing this now, but feel free to leave comment on this meta-issue.
