### ISSUE TITLE
hyper now has new crate for typed headers

### ISSUE THREAD

**Issue by izderadicka** [dekellum/hyperx#11]
It's called headers and it here  - https://docs.rs/headers/0.2.1/headers/trait.Header.html

I guess that new one will become official one?

 It's similar, but changed notably  from hyper 0.11 headers - trait is different etc.

I do not think that it's wise to maintain two very similar crates, what do you think?

**Comment by dekellum** [comment]
This was covered in #1. In particular, see final comment there.  Only time will tell if _headers_ proves stabile and compelling enough for current users of _hyperx_  (myself included) to migrate (vs. continued improvement to _hyperx_).   Closing, as nothing appears actionable.
