### ISSUE TITLE
Unusual package version ranges

### ISSUE THREAD

**Issue by roy-work** [dekellum/hyperx#36]
`Cargo.toml` specifies some overly strict version ranges:

https://github.com/dekellum/hyperx/blob/58d9a6d17d35964b007ffcfb04b7ca0c404d115f/Cargo.toml#L23-L32

This results in some really bizarre behaviors for users of `hyperx`, like packages getting downgraded when `hyperx` is pulled in. I'd like to pull this package into a crate I'm working on, to move it off an ancient version of `hyper`, but the odd range here causes an (not as, but still) old version of `hyper` to get pulled in. Both are under a RUSTSEC vuln, which is why I'd like to move the crate to `hyperx`.

Just set these equal to, e.g.,
```
bytes = "1.0.0"
```
where they span only part of a single semver compatibility range? This lets Cargo do the right thing, and pull in bug/security fixes as it can.

(Note though, that this doesn't apply to `base64`, b/c there the range is allowing multiple semver-incompatible versions.)

**Comment by nox** [comment]
@roy-work FYI https://github.com/dekellum/hyperx/pull/33

**Comment by dekellum** [comment]
The dependency and release strategy used here emphasizes and has been observed to improve MSRV guarantees, as many ≥1 crates will increase MSRV in _minor_ releases.   Note that similar dependency incompatibilities have been handled in the past on short (days) notice, and without much user awareness, but I've unfortunately been away from the project for a while this time, and many upstream changes have accumulated. 

Some day maybe rust-lang/cargo#9930 will get implemented and these ≥1 dependencies can be further broadened, but in the near term the strategy is not going to be changed.  

I've just released hyperx 1.3.1 which allows httparse 1.4 and hyper up to 0.14.11. httparse 1.5 and any future minor releases will become non-conflicting with a subsequent release including #32.
