### ISSUE TITLE
Clarify pros / cons vs typed-headers crate

### ISSUE THREAD

**Issue by shepmaster** [dekellum/hyperx#6]
In evaluating this and [typed-headers](https://github.com/sfackler/typed-headers), it'd be nice to have the crate authors expand a bit on what they think is the differentiating factors of their crate.

**Comment by dekellum** [comment]
The conversation in #1 is related. I think the most distinguishing Pro/feature of *hyperx*, thus far, is just that it preserves the work and production testing of hyper's original typed *header* module in a way that is easily auditable.  The major *Con* is it has had very little work done to date for interop with the *http* crates byte-oriented header interface and copying is required between *http* types and this crate's types.

**Comment by dekellum** [comment]
Also, the *hyperx* crate has actually been published to crates.io, since June 1, 2018!  With some additional work on *http* crate interop (alternatives #7 vs. #8) I'm going to close this. Any input on the later is much appreciated.
