### ISSUE TITLE
How does one actually set the header?

### ISSUE THREAD

**Issue by leshow** [dekellum/hyperx#9]
I'm upgrading a library of mine to hyper 0.12, came across your crate. The API my library covers requires the use of http basic auth. 

hyperx documentation shows how to create a header, which is great, but when I actually go to set the header, the compiler let's me know I need some more type annotations that I'm not sure how to provide.
example:
```rust
       let mut request = Request::builder().method(method).uri(url);
       let mut auth = Headers::new();
       auth.set(self.client.auth.clone());
       request.header(AUTHORIZATION, auth.get().unwrap()); // <--
```
output:
```
error[E0283]: type annotations required: cannot resolve `http::header::HeaderValue: http::HttpTryFrom<&_>`
   --> src/macros.rs:31:25
    |
31  |                 request.header(AUTHORIZATION, auth.get().unwrap()); // TODO try_trait
    |                         ^^^^^^

```

`auth.get()` returns some Option<H> where H: Header, so I can see why it requires an annotation, I'm just not sure what to provide.

Sorry if this is a silly question, I've been stuck here for a while.

**Comment by dekellum** [comment]
I'm not sure what `self.client` is, but I assume it provides hyper(x) typed-headers and you want to keep that for now.  

`http::request::Builder::header` wants a `HeaderValue`. The http crate implements `HttpTryFrom<&str>` and &[u8] slices for HeaderValue, so I think you need to "format" your authorization header as a String or byte slice first.  This could be simpler if there is a way to get a `Raw` header from your client.

https://docs.rs/http/0.1.14/http/header/struct.HeaderValue.html#impl-HttpTryFrom%3C%26%27a%20str%3E

**Comment by leshow** [comment]
Sorry, I should have indicated, it's an `Authorization` header from hyperx. Thanks for the help, I'll close this issue.
